Abgabe von: Mat.Nr.: 9452857 & 1113800

Before doing anything installing all needed dependencies

In [16]:
!pip3 install pandas
!pip3 install scikit-learn

# Aufgabe 1

In [17]:
import os
import pandas as pd
from sklearn.model_selection import train_test_split

In [18]:
white_raw = pd.read_csv(os.getcwd() + "/dataset/winequality-white.csv", delimiter=";")
red_raw = pd.read_csv(os.getcwd() + "/dataset/winequality-red.csv", delimiter=";")

Split wine in Test and Training Data (75% / 25%)

In [19]:
red_raw

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0               7.4             0.700         0.00             1.9      0.076   
1               7.8             0.880         0.00             2.6      0.098   
2               7.8             0.760         0.04             2.3      0.092   
3              11.2             0.280         0.56             1.9      0.075   
4               7.4             0.700         0.00             1.9      0.076   
...             ...               ...          ...             ...        ...   
1594            6.2             0.600         0.08             2.0      0.090   
1595            5.9             0.550         0.10             2.2      0.062   
1596            6.3             0.510         0.13             2.3      0.076   
1597            5.9             0.645         0.12             2.0      0.075   
1598            6.0             0.310         0.47             3.6      0.067   

      free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                    11.0                  34.0  0.99780  3.51       0.56   
1                    25.0                  67.0  0.99680  3.20       0.68   
2                    15.0                  54.0  0.99700  3.26       0.65   
3                    17.0                  60.0  0.99800  3.16       0.58   
4                    11.0                  34.0  0.99780  3.51       0.56   
...                   ...                   ...      ...   ...        ...   
1594                 32.0                  44.0  0.99490  3.45       0.58   
1595                 39.0                  51.0  0.99512  3.52       0.76   
1596                 29.0                  40.0  0.99574  3.42       0.75   
1597                 32.0                  44.0  0.99547  3.57       0.71   
1598                 18.0                  42.0  0.99549  3.39       0.66   

      alcohol  quality  
0         9.4        5  
1         9.8        5  
2         9.8        5  
3         9.8        6  
4         9.4        5  
...       ...      ...  
1594     10.5        5  
1595     11.2        6  
1596     11.0        6  
1597     10.2        5  
1598     11.0        6  

[1599 rows x 12 columns]

In [20]:
white_training_Data, white_test_data, white_training_scores, white_test_scores = (train_test_split(white_raw.drop("quality", axis=1), white_raw['quality'],test_size=0.25, random_state=39))

red_training_Data, red_test_data, red_training_scores, red_test_scores = (train_test_split(red_raw.drop("quality", axis=1), red_raw['quality'],test_size=0.25, random_state=39))

In [21]:
white_training_Data

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
3965            7.3             0.380         0.23            6.50      0.050   
3954            6.3             0.330         0.20           17.90      0.066   
580             7.4             0.410         0.66           10.80      0.051   
1637            8.1             0.120         0.49            1.20      0.042   
1310            5.2             0.365         0.08           13.50      0.041   
...             ...               ...          ...             ...        ...   
3195            7.0             0.210         0.42            5.30      0.037   
2275            7.5             0.290         0.26           14.95      0.067   
1088            7.4             0.200         0.37           16.95      0.048   
105             7.3             0.130         0.32           14.40      0.051   
3465            6.8             0.190         0.34            1.90      0.040   

      free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
3965                 18.0                 102.0  0.99304  3.10       0.55   
3954                 36.0                 161.0  0.99910  3.14       0.51   
580                  77.0                 194.0  0.99760  3.05       0.46   
1637                 43.0                 160.0  0.99340  3.13       0.48   
1310                 37.0                 142.0  0.99700  3.46       0.39   
...                   ...                   ...      ...   ...        ...   
3195                 36.0                 123.0  0.99321  3.14       0.52   
2275                 47.0                 178.0  0.99838  3.04       0.49   
1088                 43.0                 190.0  0.99950  3.03       0.42   
105                  34.0                 109.0  0.99740  3.20       0.35   
3465                 41.0                 108.0  0.99000  3.25       0.45   

      alcohol  
3965     11.2  
3954      8.8  
580       8.7  
1637      9.7  
1310      9.9  
...       ...  
3195     10.9  
2275      9.2  
1088      9.2  
105       9.2  
3465     12.9  

[3673 rows x 11 columns]

# Aufgabe 2

In [22]:
from sklearn.decomposition import PCA

In [23]:
pcaWhite = PCA(n_components='mle')
white_training_Data_new = pcaWhite.fit_transform(white_training_Data)

In [24]:
white_training_Data_new

array([[-4.00103557e+01, -6.87821434e+00,  2.11026030e+00, ...,
         1.28444382e-01,  3.49614917e-02,  9.18044474e-03],
       [ 2.21501938e+01, -5.23959619e+00,  1.06453804e+01, ...,
         7.67341894e-02, -2.11160196e-02,  1.40346026e-02],
       [ 6.45488519e+01,  2.52772212e+01,  1.13759139e+00, ...,
        -6.33555039e-02,  2.61252297e-01, -1.61776568e-02],
       ...,
       [ 5.18808060e+01, -6.30569792e+00,  8.25674853e+00, ...,
        -5.56536626e-02, -1.06617467e-01, -1.68194167e-03],
       [-2.85911312e+01,  6.74711547e+00,  9.42724438e+00, ...,
        -1.42142098e-01, -1.18927311e-01,  7.26942620e-03],
       [-2.83185232e+01,  1.36141437e+01, -3.45956834e+00, ...,
        -5.85682403e-02, -7.14035963e-02,  1.17323611e-02]])

In [25]:
pcaRed = PCA(n_components='mle')
red_training_Data_new = pcaRed.fit_transform(red_training_Data)

In [26]:
red_training_Data_new

array([[ 1.93275704e+01, -2.84958783e+00, -2.04300568e+00, ...,
         7.98022353e-02, -3.28393710e-02, -5.71154558e-03],
       [ 1.04274928e+01, -6.02523863e+00, -1.63324145e-01, ...,
        -4.08037056e-02,  6.39039091e-03,  7.47101187e-03],
       [-1.96857955e+01,  5.96053095e+00, -1.15712122e+00, ...,
         4.40640270e-02,  2.12883618e-01, -3.47578343e-02],
       ...,
       [-2.69873637e+01, -3.67923205e+00, -7.82329099e-01, ...,
         6.97301302e-02, -1.76938525e-02, -9.04143849e-03],
       [ 1.82254881e+01, -7.78759871e+00, -4.16426906e-01, ...,
        -6.42034231e-03, -1.98441864e-02, -3.01134280e-03],
       [-7.10795780e+00,  7.23303451e+00, -8.47441370e-01, ...,
         4.13081447e-02, -1.31414750e-02, -1.77071096e-02]])

# Aufgabe 3

In [27]:
white_test_data_transformed = pcaWhite.transform(white_test_data)
red_test_data_transformed = pcaRed.transform(red_test_data)

In [28]:
white_test_data_transformed

array([[-4.71972270e+01, -1.32934987e+01, -2.43728032e+00, ...,
        -5.83630646e-02,  1.87642549e-02,  4.63477946e-03],
       [-5.06996249e+01, -7.65039679e-01,  3.38087811e+00, ...,
         6.69725628e-02, -3.87760636e-02, -6.62287801e-03],
       [-4.14682770e+01,  1.10559547e+01, -2.84080182e+00, ...,
         1.26556487e-01,  2.93414861e-01, -5.91720606e-03],
       ...,
       [-1.01434923e+01, -1.19797557e+01,  5.19007289e+00, ...,
        -3.03798119e-02, -9.34350700e-03,  4.11576562e-03],
       [ 2.93704617e+01, -8.43245488e+00,  5.87848484e+00, ...,
        -2.50101199e-02, -7.24458212e-02, -5.66281933e-03],
       [ 1.13162959e+02, -3.17750964e+01,  3.74479346e+00, ...,
         1.00400578e-01,  6.27130136e-02, -1.28183484e-02]])

In [29]:
red_test_data_transformed

array([[ 9.63729178e+01, -2.03363107e+01, -7.23886655e-01, ...,
         1.53294255e-02, -6.78996066e-02,  6.34989535e-03],
       [ 1.39110646e+01,  3.77212851e-01, -3.82983197e-01, ...,
         3.31648810e-02, -5.72404607e-03,  7.76505392e-03],
       [ 9.76909623e+01, -1.45289486e+01,  1.05327717e+00, ...,
        -1.31695529e-01, -7.67790682e-02,  2.10181040e-02],
       ...,
       [-1.22257975e+01, -1.91064351e+00, -3.55225679e-01, ...,
        -1.15161785e-01, -6.11887325e-02,  1.21642748e-02],
       [-1.09202881e+01,  3.87157129e+00,  2.41167752e+00, ...,
        -1.26473823e-01, -4.55922970e-02, -5.52759808e-03],
       [-1.81823629e+01, -5.66011318e+00, -4.87560240e-01, ...,
        -5.44062853e-02, -6.95074163e-02,  7.52416669e-03]])

## Nearest Neighbor Regression

White:

In [30]:
import numpy as np
from sklearn import metrics
from sklearn.neighbors import KNeighborsRegressor
from sklearn.model_selection import RandomizedSearchCV
from sklearn.metrics import mean_absolute_error, mean_squared_error

parameters = {
    'n_neighbors': np.arange(30, 45, 1),
    'leaf_size' : np.arange(1, 8, 1),
    'weights': ['uniform', 'distance']
}
final_parameters = {
    'n_neighbors': [78],
    'leaf_size' : [1],         #egal 1-10 gleiches Ergebnis
    'weights': ['distance']
}

model = KNeighborsRegressor()
model_randomizedSearch = RandomizedSearchCV(model, param_distributions=parameters, cv=5, n_jobs=-1)

model_randomizedSearch.fit(white_training_Data_new, white_training_scores)
model_best = model_randomizedSearch.best_estimator_

print("Beste Hyperparameter: " + str(model_randomizedSearch.best_params_))
y_pred_valid = model_best.predict(white_test_data_transformed)

# Mean Absolute Error (MAE)
mae = mean_absolute_error(white_test_scores, y_pred_valid)
print("Mean Absolute Error (MAE):", mae)

# Mean Squared Error (MSE)
mse = mean_squared_error(white_test_scores, y_pred_valid)
print("Mean Squared Error (MSE):", mse)

# Root Mean Squared Error (RMSE)
rmse = np.sqrt(mse)
print("Root Mean Squared Error (RMSE):", rmse)


Beste Hyperparameter: {'weights': 'distance', 'n_neighbors': 39, 'leaf_size': 7}
Mean Absolute Error (MAE): 0.47740914404263407
Mean Squared Error (MSE): 0.49516164559387443
Root Mean Squared Error (RMSE): 0.7036772311179853


Red:

In [31]:
import numpy as np
from sklearn import metrics
from sklearn.neighbors import KNeighborsRegressor
from sklearn.model_selection import RandomizedSearchCV
from sklearn.metrics import mean_absolute_error, mean_squared_error

parameters = {
    'n_neighbors': np.arange(30, 45, 1),
    'leaf_size' : np.arange(1, 8, 1),
    'weights': ['uniform', 'distance']
}
final_parameters = {
    'n_neighbors': [78],
    'leaf_size' : [1],         #egal 1-10 gleiches Ergebnis
    'weights': ['distance']
}

model = KNeighborsRegressor()
model_randomizedSearch = RandomizedSearchCV(model, param_distributions=parameters, cv=5, n_jobs=-1)

model_randomizedSearch.fit(red_training_Data_new, red_training_scores)
model_best = model_randomizedSearch.best_estimator_

print("Beste Hyperparameter: " + str(model_randomizedSearch.best_params_))
y_pred_valid = model_best.predict(red_test_data_transformed)

# Mean Absolute Error (MAE)
mae = mean_absolute_error(red_test_scores, y_pred_valid)
print("Mean Absolute Error (MAE):", mae)

# Mean Squared Error (MSE)
mse = mean_squared_error(red_test_scores, y_pred_valid)
print("Mean Squared Error (MSE):", mse)

# Root Mean Squared Error (RMSE)
rmse = np.sqrt(mse)
print("Root Mean Squared Error (RMSE):", rmse)


Beste Hyperparameter: {'weights': 'distance', 'n_neighbors': 30, 'leaf_size': 2}
Mean Absolute Error (MAE): 0.5103222329311398
Mean Squared Error (MSE): 0.5373026188062486
Root Mean Squared Error (RMSE): 0.7330092897134719


## Support Vector Regression

White:

In [32]:
import numpy as np
from sklearn import metrics
from sklearn.svm import SVR
from sklearn.model_selection import RandomizedSearchCV
from sklearn.metrics import mean_absolute_error, mean_squared_error


parameters = {
    'kernel': ['rbf', 'poly', 'sigmoid'],
    #'gamma' : ['scale', 'auto'],
    'epsilon': np.linspace(1, 42000, 100),
    'C': np.linspace(0.01, 5000, 100),
}
final_parameters = {
    'n_neighbors': [78],
    'leaf_size' : [1],         #egal 1-10 gleiches Ergebnis
    'weights': ['distance']
}

model = SVR()
model_randomizedSearch = RandomizedSearchCV(model, param_distributions=parameters, cv=5, n_jobs=-1)

model_randomizedSearch.fit(white_training_Data_new, white_training_scores)
model_best = model_randomizedSearch.best_estimator_

print("Beste Hyperparameter: " + str(model_randomizedSearch.best_params_))
y_pred_valid = model_best.predict(white_test_data_transformed)

# Mean Absolute Error (MAE)
mae = mean_absolute_error(white_test_scores, y_pred_valid)
print("Mean Absolute Error (MAE):", mae)

# Mean Squared Error (MSE)
mse = mean_squared_error(white_test_scores, y_pred_valid)
print("Mean Squared Error (MSE):", mse)

# Root Mean Squared Error (RMSE)
rmse = np.sqrt(mse)
print("Root Mean Squared Error (RMSE):", rmse)


Beste Hyperparameter: {'kernel': 'rbf', 'epsilon': 1.0, 'C': 505.05949494949493}
Mean Absolute Error (MAE): 0.6073450497065087
Mean Squared Error (MSE): 0.6070314029654152
Root Mean Squared Error (RMSE): 0.7791222002776043


Red:

In [33]:
import numpy as np
from sklearn import metrics
from sklearn.svm import SVR
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import mean_absolute_error, mean_squared_error


parameters = {
    'kernel': ['rbf', 'poly', 'sigmoid'],
    #'gamma' : ['scale', 'auto'],
    'epsilon': np.linspace(1, 42000, 100),
    'C': np.linspace(0.01, 100, 100),
}
final_parameters = {
    'n_neighbors': [78],
    'leaf_size' : [1],         #egal 1-10 gleiches Ergebnis
    'weights': ['distance']
}

model = SVR()
model_randomizedSearch = RandomizedSearchCV(model, param_distributions=parameters, cv=5, n_jobs=-1)

model_randomizedSearch.fit(red_training_Data_new, red_training_scores)
model_best = model_randomizedSearch.best_estimator_

print("Beste Hyperparameter: " + str(model_randomizedSearch.best_params_))
y_pred_valid = model_best.predict(red_test_data_transformed)

# Mean Absolute Error (MAE)
mae = mean_absolute_error(red_test_scores, y_pred_valid)
print("Mean Absolute Error (MAE):", mae)

# Mean Squared Error (MSE)
mse = mean_squared_error(red_test_scores, y_pred_valid)
print("Mean Squared Error (MSE):", mse)

# Root Mean Squared Error (RMSE)
rmse = np.sqrt(mse)
print("Root Mean Squared Error (RMSE):", rmse)


Beste Hyperparameter: {'kernel': 'poly', 'epsilon': 26727.636363636364, 'C': 49.5}
Mean Absolute Error (MAE): 0.745
Mean Squared Error (MSE): 0.785
Root Mean Squared Error (RMSE): 0.8860022573334675
